const LOGOUT = 'AUTH/LOGOUT';
const SAVE_BACKUP = 'AUTH/SAVE_BACKUP';
const CREATE_CRYPTO_WALLET = 'AUTH/CREATE_CRYPTO_WALLET';


export default {
    LOGOUT,
    SAVE_BACKUP,
    CREATE_CRYPTO_WALLET,
};
