const CREATE_CRYPTO_WALLET = 'CRYPTO/CREATE_CRYPTO_WALLET';

const UPDATE_CRYPTO_LIST = 'CRYPTO/UPDATE_CRYPTO_LIST';
const UPDATE_CRYPTO_BALANCE = 'CRYPTO/UPDATE_CRYPTO_BALANCE';


export default {
    CREATE_CRYPTO_WALLET,

    UPDATE_CRYPTO_LIST,
    UPDATE_CRYPTO_BALANCE,
};
