const APP_STATE_CHANGE = 'app-state/CHANGE';
const APP_COLLAPSED = 'app-state/COLLAPSED';
const APP_EXPANDED = 'app-state/EXPANDED';

const APP_STATE_SKIP_CHANGE = 'app-state/APP_STATE_SKIP_CHANGE';
const APP_STATE_LOADING_CHANGE = 'app-state/APP_STATE_LOADING_CHANGE';

const APP_LOCALIZATION_CHANGE = 'app-state/LOCALIZATION_CHANGE';

export default {
    APP_STATE_CHANGE,
    APP_COLLAPSED,
    APP_EXPANDED,

    APP_STATE_SKIP_CHANGE,
    APP_STATE_LOADING_CHANGE,

    APP_LOCALIZATION_CHANGE,
};
