const SIGN_UP = 'AUTH/SIGN_UP';
const SIGN_IN = 'AUTH/SIGN_IN';
const LOGOUT = 'AUTH/LOGOUT';
const BACKUP_SAVE = 'AUTH/BACKUP_SAVE';
const BACKUP_SAVE_FAIL = 'AUTH/BACKUP_SAVE_FAIL';
const BACKUP_SAVE_SUCCESS = 'AUTH/BACKUP_SAVE_SUCCESS';
const CREATE_ZORKA_WALLET = 'AUTH/CREATE_ZORKA_WALLET';
const ENTER_SECRET_PHRASE = 'AUTH/ENTER_SECRET_PHRASE';


export default {
    LOGOUT,
    SIGN_IN,
    SIGN_UP,
    BACKUP_SAVE,
    BACKUP_SAVE_FAIL,
    BACKUP_SAVE_SUCCESS,
    CREATE_ZORKA_WALLET,
    ENTER_SECRET_PHRASE,
};
