const DEVICE_ORIENTATION: {
  PORTRAIT: DEVICE_ORIENTATION_PORTRAIT;
  LANDSCAPE: DEVICE_ORIENTATION_LANDSCAPE;
} = {
  PORTRAIT: 'portrait',
  LANDSCAPE: 'landscape',
};

export default DEVICE_ORIENTATION;
