const CREATE_CRYPTO_WALLET = 'CRYPTO/CREATE_CRYPTO_WALLET';

const UPDATE_CRYPTO_LIST = 'CRYPTO/UPDATE_CRYPTO_LIST';
const CRYPTO_LIST_UPDATED = 'CRYPTO/CRYPTO_LIST_UPDATED';
const UPDATE_CRYPTO_WALLET_INFO = 'CRYPTO/UPDATE_CRYPTO_WALLET_INFO';

const CREATE_TRANSACTION = 'CRYPTO/CREATE_TRANSACTION';


export default {
    CREATE_CRYPTO_WALLET,

    UPDATE_CRYPTO_LIST,
    CRYPTO_LIST_UPDATED,
    UPDATE_CRYPTO_WALLET_INFO,

    CREATE_TRANSACTION,
};
