const CREATE_CRYPTO_WALLET = 'CRYPTO/CREATE_CRYPTO_WALLET';

const UPDATE_CRYPTO_LIST = 'CRYPTO/UPDATE_CRYPTO_LIST';
const UPDATE_CRYPTO_WALLET_INFO = 'CRYPTO/UPDATE_CRYPTO_WALLET_INFO';

const CREATE_TRANSACTION = 'CRYPTO/CREATE_TRANSACTION';


export default {
    CREATE_CRYPTO_WALLET,

    UPDATE_CRYPTO_LIST,
    UPDATE_CRYPTO_WALLET_INFO,

    CREATE_TRANSACTION,
};
