const POP = 'NAVIGATION/POP';
const PUSH = 'NAVIGATION/PUSH';
const SHOW_MODAL = 'NAVIGATION/SHOW_MODAL';
const TOGGLE_SIDE_MENU = 'NAVIGATION/TOGGLE_SIDE_MENU';

export default {
    POP,
    PUSH,
    SHOW_MODAL,
    TOGGLE_SIDE_MENU,
};
